# Generated by Django 3.0.3 on 2020-03-01 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['image_category']},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['image_title']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['location']},
        ),
    ]
