# Generated by Django 3.0.3 on 2020-02-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(default='category', max_length=60),
        ),
    ]
