# Generated by Django 3.0.3 on 2020-02-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='post_image',
            field=models.ImageField(default='image', upload_to='images/'),
        ),
    ]
