# Generated by Django 3.0.3 on 2020-02-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_image_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_description',
            field=models.TextField(default='description', max_length=200),
        ),
        migrations.AddField(
            model_name='image',
            name='image_title',
            field=models.CharField(default='title', max_length=100),
        ),
    ]
